# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: externaldns-operator
  namespace: openshift-externaldns-operator
