# Deployment with default values
# ExternalDNS specific values are applied at runtime.
kind: Deployment
apiVersion: apps/v1
# name and namespace are set at runtime.
spec:
  template:
    spec:
      serviceAccountName: externaldns
      priorityClassName: system-cluster-critical
      containers:
        - name: externaldns
          # image and args are set at runtime.
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics
            containerPort: 7979
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
